CREATE TABLE IF NOT EXISTS email_templates (
  id        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `key`     VARCHAR(32)  NOT NULL,
  lang      VARCHAR(5)   NOT NULL,
  subject   VARCHAR(255) NOT NULL,
  body_html TEXT         NOT NULL,
  UNIQUE KEY uq_tpl_key_lang (`key`, lang)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO email_templates (`key`, lang, subject, body_html) VALUES
('welcome','en','Welcome to Crush','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">Welcome to Crush, {{name}}</h1><p>Your account is ready. Sign in and add a few cute details to your profile.</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Sign in</a></p><p style="color:#999;font-size:12px">Or paste this link: {{link}}</p></div>'),
('welcome','vi','Chao mung den voi Crush','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">Chao mung den voi Crush, {{name}}</h1><p>Tai khoan cua ban da san sang. Dang nhap va them vai thong tin de hoan thien ho so.</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Dang nhap</a></p><p style="color:#999;font-size:12px">Hoac dan lien ket nay: {{link}}</p></div>'),
('welcome','ko','Crush에 오신 것을 환영합니다','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{name}}님, Crush에 오신 것을 환영합니다</h1><p>계정이 준비되었습니다. 로그인하고 프로필을 완성해 보세요.</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">로그인</a></p><p style="color:#999;font-size:12px">또는 이 링크를 붙여넣으세요: {{link}}</p></div>'),
('invite','en','You have a crush invite','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{senderLabel}} has a crush on you</h1><p>{{message}}</p><p>Tap below to pick a date, a meal, and where to meet.</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Open my invite</a></p><p style="color:#bbb;font-size:11px">Not interested? Block and report: {{unsubscribe}}</p></div>'),
('invite','vi','Ban nhan duoc loi moi hen ho','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{senderLabel}} dang thich ban</h1><p>{{message}}</p><p>Nhan vao nut ben duoi de chon ngay, mon an va dia diem gap nhau.</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Mo loi moi</a></p><p style="color:#bbb;font-size:11px">Khong quan tam? Chan va bao cao: {{unsubscribe}}</p></div>'),
('invite','ko','초대장이 도착했어요','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{senderLabel}}님이 당신을 좋아합니다</h1><p>{{message}}</p><p>아래를 눌러 날짜와 식사, 만날 장소를 골라주세요.</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">초대장 열기</a></p><p style="color:#bbb;font-size:11px">관심이 없으신가요? 차단 및 신고: {{unsubscribe}}</p></div>'),
('result','en','{{crushName}} answered your invite','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{crushName}} said yes</h1><p>Here is what they picked. The calendar invite is attached.</p><ul style="line-height:1.7"><li><strong>When:</strong> {{when}}</li><li><strong>Craving:</strong> {{meal}}</li><li><strong>Pickup:</strong> {{place}}</li><li><strong>Map:</strong> {{mapHref}}</li></ul></div>'),
('result','vi','{{crushName}} da tra loi loi moi','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{crushName}} dong y roi</h1><p>Day la lua chon cua ho. Loi moi lich da duoc dinh kem.</p><ul style="line-height:1.7"><li><strong>Khi nao:</strong> {{when}}</li><li><strong>Mon:</strong> {{meal}}</li><li><strong>Don o:</strong> {{place}}</li><li><strong>Ban do:</strong> {{mapHref}}</li></ul></div>'),
('result','ko','{{crushName}}님이 초대에 응답했어요','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><h1 style="color:#ff3d8b">{{crushName}}님이 좋다고 했어요</h1><p>고른 내용은 다음과 같아요. 캘린더 초대가 첨부되어 있습니다.</p><ul style="line-height:1.7"><li><strong>언제:</strong> {{when}}</li><li><strong>메뉴:</strong> {{meal}}</li><li><strong>픽업:</strong> {{place}}</li><li><strong>지도:</strong> {{mapHref}}</li></ul></div>'),
('magic','en','Your Crush sign-in link','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><p>Tap to sign in to Crush:</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Sign in</a></p><p style="color:#999;font-size:12px">Or paste: {{link}}</p></div>'),
('magic','vi','Lien ket dang nhap Crush','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><p>Nhan de dang nhap vao Crush:</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">Dang nhap</a></p><p style="color:#999;font-size:12px">Hoac dan: {{link}}</p></div>'),
('magic','ko','Crush 로그인 링크','<div style="font-family:system-ui,sans-serif;max-width:480px;margin:0 auto;padding:24px"><p>탭하여 Crush에 로그인하세요:</p><p><a href="{{link}}" style="display:inline-block;padding:12px 20px;background:#ff3d8b;color:#fff;border-radius:12px;text-decoration:none;font-weight:700">로그인</a></p><p style="color:#999;font-size:12px">또는 붙여넣기: {{link}}</p></div>')
ON DUPLICATE KEY UPDATE subject = VALUES(subject), body_html = VALUES(body_html);
