INSERT INTO ui_translations (lang, `key`, value) VALUES

-- Send a crush invite
('vi','Send a crush invite','Gửi lời mời Crush'),
('es','Send a crush invite','Mandar una invitación a tu crush'),
('zh','Send a crush invite','发起一个约会邀请'),
('hi','Send a crush invite','अपने crush को invite भेजो'),
('pt','Send a crush invite','Mandar um convite pro seu crush'),
('fr','Send a crush invite','Envoyer une invitation à ton crush'),
('ko','Send a crush invite','좋아하는 사람에게 초대장 보내기'),
('ja','Send a crush invite','好きな人にCrushを送ろう'),
('th','Send a crush invite','ส่งคำเชิญ Crush'),

-- How will you send it?
('vi','How will you send it?','Bạn muốn gửi kiểu nào?'),
('es','How will you send it?','¿Cómo lo vas a enviar?'),
('zh','How will you send it?','你打算怎么发给他/她？'),
('hi','How will you send it?','इसे कैसे भेजोगे?'),
('pt','How will you send it?','Como você vai enviar?'),
('fr','How will you send it?','Tu vas l''envoyer comment ?'),
('ko','How will you send it?','어떻게 보낼 거야?'),
('ja','How will you send it?','どうやって送る？'),
('th','How will you send it?','จะส่งยังไงดี?'),

-- Email it to them
('vi','Email it to them','Gửi email cho họ'),
('es','Email it to them','Mandárselo por email'),
('zh','Email it to them','发邮件给他/她'),
('hi','Email it to them','उन्हें email करो'),
('pt','Email it to them','Mandar por email'),
('fr','Email it to them','Leur envoyer par email'),
('ko','Email it to them','이메일로 보내기'),
('ja','Email it to them','メールで送る'),
('th','Email it to them','ส่งอีเมลหาเขา/เธอ'),

-- I'll share the link
('vi','I''ll share the link','Tôi sẽ tự gửi link'),
('es','I''ll share the link','Yo le paso el link'),
('zh','I''ll share the link','我自己把链接发给他/她'),
('hi','I''ll share the link','मैं खुद link share करूंगा/करूंगी'),
('pt','I''ll share the link','Eu mesmo mando o link'),
('fr','I''ll share the link','Je lui enverrai le lien moi-même'),
('ko','I''ll share the link','내가 직접 링크 보낼게'),
('ja','I''ll share the link','自分でリンクを送るよ'),
('th','I''ll share the link','ฉันจะส่งลิงก์เอง'),

-- Their email
('vi','Their email','Email của họ'),
('es','Their email','Su email'),
('zh','Their email','他/她的邮箱'),
('hi','Their email','उनका email'),
('pt','Their email','Email dele/dela'),
('fr','Their email','Son email'),
('ko','Their email','상대방 이메일'),
('ja','Their email','相手のメアド'),
('th','Their email','อีเมลของเขา/เธอ'),

-- Their name
('vi','Their name','Tên của họ'),
('es','Their name','Su nombre'),
('zh','Their name','他/她的名字'),
('hi','Their name','उनका नाम'),
('pt','Their name','Nome dele/dela'),
('fr','Their name','Son prénom'),
('ko','Their name','상대방 이름'),
('ja','Their name','相手の名前'),
('th','Their name','ชื่อของเขา/เธอ'),

-- A little message (optional)
('vi','A little message (optional)','Nhắn gì đó đi (không bắt buộc)'),
('es','A little message (optional)','Un mensajito (opcional)'),
('zh','A little message (optional)','留句话吧（可选）'),
('hi','A little message (optional)','कुछ लिखो (optional)'),
('pt','A little message (optional)','Uma mensagenzinha (opcional)'),
('fr','A little message (optional)','Un petit mot (facultatif)'),
('ko','A little message (optional)','한 마디 남기기 (선택)'),
('ja','A little message (optional)','ひとこと添えて（任意）'),
('th','A little message (optional)','ฝากข้อความสักหน่อย (ไม่บังคับ)'),

-- When should they pick?
('vi','When should they pick?','Khi nào thì họ chọn?'),
('es','When should they pick?','¿Cuándo eligen ellos?'),
('zh','When should they pick?','他/她什么时候选？'),
('hi','When should they pick?','वो कब चुनेंगे?'),
('pt','When should they pick?','Quando eles vão escolher?'),
('fr','When should they pick?','Quand doivent-ils choisir ?'),
('ko','When should they pick?','언제 고르게 할 거야?'),
('ja','When should they pick?','いつ選んでもらう？'),
('th','When should they pick?','ให้เขา/เธอเลือกตอนไหน?'),

-- Any time (final)
('vi','Any time (final)','Bất cứ lúc nào cũng được (chốt luôn)'),
('es','Any time (final)','Cuando quieran (definitivo)'),
('zh','Any time (final)','随时都行（直接定了）'),
('hi','Any time (final)','कभी भी (पक्का)'),
('pt','Any time (final)','Qualquer hora (definitivo)'),
('fr','Any time (final)','N''importe quand (c''est décidé)'),
('ko','Any time (final)','아무 때나 (확정)'),
('ja','Any time (final)','いつでもOK（確定）'),
('th','Any time (final)','เมื่อไหรก็ได้ (ยืนยัน)'),

-- They propose, I confirm
('vi','They propose, I confirm','Họ đề xuất, tôi xác nhận'),
('es','They propose, I confirm','Ellos proponen, yo confirmo'),
('zh','They propose, I confirm','他/她来提，我来定'),
('hi','They propose, I confirm','वो suggest करें, मैं confirm करूं'),
('pt','They propose, I confirm','Eles sugerem, eu confirmo'),
('fr','They propose, I confirm','Ils proposent, je confirme'),
('ko','They propose, I confirm','상대가 제안하면 내가 확인'),
('ja','They propose, I confirm','相手が提案、私が確認'),
('th','They propose, I confirm','เขา/เธอเสนอ ฉันยืนยัน'),

-- Send anonymously (a secret admirer)
('vi','Send anonymously (a secret admirer)','Gửi ẩn danh (người hâm mộ bí ẩn)'),
('es','Send anonymously (a secret admirer)','Enviar de forma anónima (un admirador secreto)'),
('zh','Send anonymously (a secret admirer)','匿名发送（神秘仰慕者）'),
('hi','Send anonymously (a secret admirer)','Anonymous भेजो (एक secret admirer)'),
('pt','Send anonymously (a secret admirer)','Enviar anonimamente (um admirador secreto)'),
('fr','Send anonymously (a secret admirer)','Envoyer anonymement (un admirateur secret)'),
('ko','Send anonymously (a secret admirer)','익명으로 보내기 (비밀 팬)'),
('ja','Send anonymously (a secret admirer)','匿名で送る（秘密のファン）'),
('th','Send anonymously (a secret admirer)','ส่งแบบไม่ระบุชื่อ (แฟนลับ)'),

-- Reveal me after they respond
('vi','Reveal me after they respond','Tiết lộ tôi sau khi họ trả lời'),
('es','Reveal me after they respond','Revelarme cuando ellos respondan'),
('zh','Reveal me after they respond','等他/她回复后再揭晓我'),
('hi','Reveal me after they respond','उनके जवाब के बाद मुझे reveal करो'),
('pt','Reveal me after they respond','Me revelar depois que eles responderem'),
('fr','Reveal me after they respond','Me révéler après leur réponse'),
('ko','Reveal me after they respond','상대가 답하면 내 정체 공개'),
('ja','Reveal me after they respond','相手が返事したら私を明かして'),
('th','Reveal me after they respond','เปิดเผยตัวตนหลังจากเขา/เธอตอบกลับ'),

-- A spot to suggest?
('vi','A spot to suggest?','Có chỗ nào muốn gợi ý không?'),
('es','A spot to suggest?','¿Tienes algún lugar en mente?'),
('zh','A spot to suggest?','有想推荐的地方吗？'),
('hi','A spot to suggest?','कोई जगह suggest करनी है?'),
('pt','A spot to suggest?','Tem algum lugar pra sugerir?'),
('fr','A spot to suggest?','Un endroit à suggérer ?'),
('ko','A spot to suggest?','장소 추천할 거 있어?'),
('ja','A spot to suggest?','おすすめの場所はある？'),
('th','A spot to suggest?','มีสถานที่อยากแนะนำไหม?'),

-- I'm open — they pick
('vi','I''m open — they pick','Tôi thoải mái — để họ chọn'),
('es','I''m open — they pick','Me da igual — que elijan ellos'),
('zh','I''m open — they pick','都行 — 让他/她来选'),
('hi','I''m open — they pick','कोई भी — वो चुनें'),
('pt','I''m open — they pick','Tanto faz — deixa eles escolherem'),
('fr','I''m open — they pick','Peu importe — c''est eux qui choisissent'),
('ko','I''m open — they pick','상관없어 — 상대가 고르게'),
('ja','I''m open — they pick','なんでもOK — 相手に選ばせる'),
('th','I''m open — they pick','โอเคทุกที่ — ให้เขา/เธอเลือกเลย'),

-- Let's do a vibe
('vi','Let''s do a vibe','Chọn theo vibe đi'),
('es','Let''s do a vibe','Vamos a elegir por ambiente'),
('zh','Let''s do a vibe','按感觉来选吧'),
('hi','Let''s do a vibe','Vibe के हिसाब से चुनते हैं'),
('pt','Let''s do a vibe','Bora por vibe'),
('fr','Let''s do a vibe','On choisit par ambiance'),
('ko','Let''s do a vibe','분위기로 골라봐'),
('ja','Let''s do a vibe','雰囲気で選ぼう'),
('th','Let''s do a vibe','เลือกตามบรรยากาศเลย'),

-- restaurant name
('vi','restaurant name','tên nhà hàng'),
('es','restaurant name','nombre del restaurante'),
('zh','restaurant name','餐厅名称'),
('hi','restaurant name','रेस्तरां का नाम'),
('pt','restaurant name','nome do restaurante'),
('fr','restaurant name','nom du restaurant'),
('ko','restaurant name','식당 이름'),
('ja','restaurant name','お店の名前'),
('th','restaurant name','ชื่อร้านอาหาร'),

-- maps link (optional)
('vi','maps link (optional)','link bản đồ (không bắt buộc)'),
('es','maps link (optional)','link de maps (opcional)'),
('zh','maps link (optional)','地图链接（可选）'),
('hi','maps link (optional)','maps link (optional)'),
('pt','maps link (optional)','link do maps (opcional)'),
('fr','maps link (optional)','lien maps (facultatif)'),
('ko','maps link (optional)','지도 링크 (선택)'),
('ja','maps link (optional)','マップのリンク（任意）'),
('th','maps link (optional)','ลิงก์แผนที่ (ไม่บังคับ)'),

-- cuisine
('vi','cuisine','ẩm thực'),
('es','cuisine','tipo de cocina'),
('zh','cuisine','菜系'),
('hi','cuisine','cuisine'),
('pt','cuisine','culinária'),
('fr','cuisine','type de cuisine'),
('ko','cuisine','요리 종류'),
('ja','cuisine','料理のジャンル'),
('th','cuisine','ประเภทอาหาร'),

-- Other
('vi','Other','Khác'),
('es','Other','Otro'),
('zh','Other','其他'),
('hi','Other','अन्य'),
('pt','Other','Outro'),
('fr','Other','Autre'),
('ko','Other','기타'),
('ja','Other','その他'),
('th','Other','อื่น ๆ'),

-- Add another place
('vi','Add another place','Thêm địa điểm khác'),
('es','Add another place','Agregar otro lugar'),
('zh','Add another place','再加一个地方'),
('hi','Add another place','एक और जगह add करो'),
('pt','Add another place','Adicionar outro lugar'),
('fr','Add another place','Ajouter un autre endroit'),
('ko','Add another place','장소 하나 더 추가'),
('ja','Add another place','場所をもう一つ追加'),
('th','Add another place','เพิ่มสถานที่อีกแห่ง'),

-- Create my invite
('vi','Create my invite','Tạo lời mời của tôi'),
('es','Create my invite','Crear mi invitación'),
('zh','Create my invite','创建我的邀请'),
('hi','Create my invite','मेरा invite बनाओ'),
('pt','Create my invite','Criar meu convite'),
('fr','Create my invite','Créer mon invitation'),
('ko','Create my invite','내 초대장 만들기'),
('ja','Create my invite','招待状を作る'),
('th','Create my invite','สร้างคำเชิญของฉัน'),

-- Creating as
('vi','Creating as','Đang tạo với tên'),
('es','Creating as','Creando como'),
('zh','Creating as','正在以此身份创建'),
('hi','Creating as','इस नाम से बना रहे हैं'),
('pt','Creating as','Criando como'),
('fr','Creating as','Création en tant que'),
('ko','Creating as','로 만드는 중'),
('ja','Creating as','として作成中'),
('th','Creating as','กำลังสร้างในชื่อ'),

-- not you?
('vi','not you?','không phải bạn?'),
('es','not you?','¿no eres tú?'),
('zh','not you?','不是你？'),
('hi','not you?','आप नहीं हैं?'),
('pt','not you?','não é você?'),
('fr','not you?','c''est pas toi ?'),
('ko','not you?','너 아니야?'),
('ja','not you?','あなたじゃない？'),
('th','not you?','ไม่ใช่คุณเหรอ?'),

-- use another email
('vi','use another email','dùng email khác'),
('es','use another email','usar otro email'),
('zh','use another email','用另一个邮箱'),
('hi','use another email','दूसरा email use करो'),
('pt','use another email','usar outro email'),
('fr','use another email','utiliser un autre email'),
('ko','use another email','다른 이메일 쓰기'),
('ja','use another email','別のメアドを使う'),
('th','use another email','ใช้อีเมลอื่น'),

-- log in
('vi','log in','đăng nhập'),
('es','log in','iniciar sesión'),
('zh','log in','登录'),
('hi','log in','log in करो'),
('pt','log in','entrar'),
('fr','log in','se connecter'),
('ko','log in','로그인'),
('ja','log in','ログイン'),
('th','log in','เข้าสู่ระบบ'),

-- Map preview
('vi','Map preview','Xem trước bản đồ'),
('es','Map preview','Vista previa del mapa'),
('zh','Map preview','地图预览'),
('hi','Map preview','Map preview'),
('pt','Map preview','Pré-visualização do mapa'),
('fr','Map preview','Aperçu de la carte'),
('ko','Map preview','지도 미리보기'),
('ja','Map preview','マップのプレビュー'),
('th','Map preview','ดูตัวอย่างแผนที่'),

-- Coffee
('vi','Coffee','Cà phê'),
('es','Coffee','Café'),
('zh','Coffee','咖啡'),
('hi','Coffee','कॉफी'),
('pt','Coffee','Café'),
('fr','Coffee','Café'),
('ko','Coffee','커피'),
('ja','Coffee','カフェ'),
('th','Coffee','กาแฟ'),

-- Brunch
('vi','Brunch','Bữa sáng muộn'),
('es','Brunch','Brunch'),
('zh','Brunch','早午餐'),
('hi','Brunch','ब्रंच'),
('pt','Brunch','Brunch'),
('fr','Brunch','Brunch'),
('ko','Brunch','브런치'),
('ja','Brunch','ブランチ'),
('th','Brunch','บรันช์'),

-- Lunch
('vi','Lunch','Bữa trưa'),
('es','Lunch','Almuerzo'),
('zh','Lunch','午餐'),
('hi','Lunch','दोपहर का खाना'),
('pt','Lunch','Almoço'),
('fr','Lunch','Déjeuner'),
('ko','Lunch','점심'),
('ja','Lunch','ランチ'),
('th','Lunch','อาหารกลางวัน'),

-- Dinner
('vi','Dinner','Bữa tối'),
('es','Dinner','Cena'),
('zh','Dinner','晚餐'),
('hi','Dinner','रात का खाना'),
('pt','Dinner','Jantar'),
('fr','Dinner','Dîner'),
('ko','Dinner','저녁'),
('ja','Dinner','ディナー'),
('th','Dinner','อาหารเย็น'),

-- Dessert
('vi','Dessert','Tráng miệng'),
('es','Dessert','Postre'),
('zh','Dessert','甜点'),
('hi','Dessert','मिठाई'),
('pt','Dessert','Sobremesa'),
('fr','Dessert','Dessert'),
('ko','Dessert','디저트'),
('ja','Dessert','スイーツ'),
('th','Dessert','ของหวาน'),

-- Drinks
('vi','Drinks','Đồ uống'),
('es','Drinks','Copas'),
('zh','Drinks','喝一杯'),
('hi','Drinks','ड्रिंक्स'),
('pt','Drinks','Drinks'),
('fr','Drinks','Verre'),
('ko','Drinks','술 한잔'),
('ja','Drinks','飲み'),
('th','Drinks','เครื่องดื่ม'),

-- Your invites
('vi','Your invites','Lời mời của bạn'),
('es','Your invites','Tus invitaciones'),
('zh','Your invites','我的邀请'),
('hi','Your invites','आपके invites'),
('pt','Your invites','Seus convites'),
('fr','Your invites','Tes invitations'),
('ko','Your invites','내 초대장'),
('ja','Your invites','あなたの招待状'),
('th','Your invites','คำเชิญของคุณ'),

-- Send a new crush invite
('vi','Send a new crush invite','Gửi lời mời Crush mới'),
('es','Send a new crush invite','Mandar una nueva invitación a tu crush'),
('zh','Send a new crush invite','发起新的约会邀请'),
('hi','Send a new crush invite','नया crush invite भेजो'),
('pt','Send a new crush invite','Mandar um novo convite pro crush'),
('fr','Send a new crush invite','Envoyer une nouvelle invitation à ton crush'),
('ko','Send a new crush invite','새 초대장 보내기'),
('ja','Send a new crush invite','新しいCrushを送る'),
('th','Send a new crush invite','ส่งคำเชิญ Crush ใหม่'),

-- No invites yet. Send your first one above.
('vi','No invites yet. Send your first one above.','Chưa có lời mời nào. Gửi cái đầu tiên ngay đi!'),
('es','No invites yet. Send your first one above.','Todavía sin invitaciones. ¡Manda tu primera arriba!'),
('zh','No invites yet. Send your first one above.','还没有邀请。从上面发出你的第一个吧！'),
('hi','No invites yet. Send your first one above.','अभी कोई invite नहीं है। ऊपर से अपना पहला भेजो।'),
('pt','No invites yet. Send your first one above.','Nenhum convite ainda. Manda o primeiro lá em cima!'),
('fr','No invites yet. Send your first one above.','Pas encore d''invitation. Envoie ta première là-haut !'),
('ko','No invites yet. Send your first one above.','아직 초대장 없어. 위에서 첫 번째 보내봐!'),
('ja','No invites yet. Send your first one above.','まだ招待状がない。上から最初の一枚を送ろう！'),
('th','No invites yet. Send your first one above.','ยังไม่มีคำเชิญ ส่งอันแรกด้านบนเลย!'),

-- A secret crush
('vi','A secret crush','Người thầm thương bí ẩn'),
('es','A secret crush','Un crush secreto'),
('zh','A secret crush','一个秘密暗恋'),
('hi','A secret crush','एक secret crush'),
('pt','A secret crush','Um crush secreto'),
('fr','A secret crush','Un crush secret'),
('ko','A secret crush','비밀 짝사랑'),
('ja','A secret crush','秘密のときめき'),
('th','A secret crush','แอบชอบคนนึง'),

-- Waiting
('vi','Waiting','Đang chờ'),
('es','Waiting','Esperando'),
('zh','Waiting','等待中'),
('hi','Waiting','इंतज़ार'),
('pt','Waiting','Aguardando'),
('fr','Waiting','En attente'),
('ko','Waiting','기다리는 중'),
('ja','Waiting','待ってる'),
('th','Waiting','รอคำตอบ'),

-- Answered
('vi','Answered','Đã trả lời'),
('es','Answered','Respondido'),
('zh','Answered','已回复'),
('hi','Answered','जवाब मिल गया'),
('pt','Answered','Respondido'),
('fr','Answered','Répondu'),
('ko','Answered','답장 왔어'),
('ja','Answered','返事あり'),
('th','Answered','ตอบแล้ว'),

-- Needs you
('vi','Needs you','Cần bạn xác nhận'),
('es','Needs you','Te necesita'),
('zh','Needs you','等你确认'),
('hi','Needs you','आपकी ज़रूरत है'),
('pt','Needs you','Precisa de você'),
('fr','Needs you','T''attend'),
('ko','Needs you','네 차례야'),
('ja','Needs you','あなたが必要'),
('th','Needs you','รอการยืนยันจากคุณ'),

-- Confirmed
('vi','Confirmed','Đã xác nhận'),
('es','Confirmed','Confirmado'),
('zh','Confirmed','已确认'),
('hi','Confirmed','Confirmed'),
('pt','Confirmed','Confirmado'),
('fr','Confirmed','Confirmé'),
('ko','Confirmed','확정됐어'),
('ja','Confirmed','確定'),
('th','Confirmed','ยืนยันแล้ว'),

-- Closed
('vi','Closed','Đã đóng'),
('es','Closed','Cerrado'),
('zh','Closed','已结束'),
('hi','Closed','बंद'),
('pt','Closed','Encerrado'),
('fr','Closed','Fermé'),
('ko','Closed','종료'),
('ja','Closed','終了'),
('th','Closed','ปิดแล้ว'),

-- View
('vi','View','Xem'),
('es','View','Ver'),
('zh','View','查看'),
('hi','View','देखें'),
('pt','View','Ver'),
('fr','View','Voir'),
('ko','View','보기'),
('ja','View','見る'),
('th','View','ดู'),

-- Copy link
('vi','Copy link','Sao chép link'),
('es','Copy link','Copiar enlace'),
('zh','Copy link','复制链接'),
('hi','Copy link','Link copy करो'),
('pt','Copy link','Copiar link'),
('fr','Copy link','Copier le lien'),
('ko','Copy link','링크 복사'),
('ja','Copy link','リンクをコピー'),
('th','Copy link','คัดลอกลิงก์'),

-- Your invite is ready
('vi','Your invite is ready','Lời mời của bạn đã sẵn sàng'),
('es','Your invite is ready','Tu invitación está lista'),
('zh','Your invite is ready','你的邀请已准备好'),
('hi','Your invite is ready','आपका invite तैयार है'),
('pt','Your invite is ready','Seu convite está pronto'),
('fr','Your invite is ready','Ton invitation est prête'),
('ko','Your invite is ready','초대장 완성됐어!'),
('ja','Your invite is ready','招待状が完成したよ'),
('th','Your invite is ready','คำเชิญของคุณพร้อมแล้ว'),

-- Share this private link with
('vi','Share this private link with','Chia sẻ link riêng tư này với'),
('es','Share this private link with','Comparte este link privado con'),
('zh','Share this private link with','把这个私密链接分享给'),
('hi','Share this private link with','यह private link share करो'),
('pt','Share this private link with','Compartilhe este link privado com'),
('fr','Share this private link with','Partage ce lien privé avec'),
('ko','Share this private link with','이 비공개 링크를 공유하기'),
('ja','Share this private link with','このプライベートリンクをシェアして'),
('th','Share this private link with','แชร์ลิงก์ส่วนตัวนี้กับ'),

-- Share your private invite link:
('vi','Share your private invite link:','Chia sẻ link mời riêng tư của bạn:'),
('es','Share your private invite link:','Comparte tu link de invitación privado:'),
('zh','Share your private invite link:','分享你的私密邀请链接：'),
('hi','Share your private invite link:','अपना private invite link share करो:'),
('pt','Share your private invite link:','Compartilhe seu link privado de convite:'),
('fr','Share your private invite link:','Partage ton lien d''invitation privé :'),
('ko','Share your private invite link:','비공개 초대 링크 공유하기:'),
('ja','Share your private invite link:','プライベートな招待リンクをシェアして：'),
('th','Share your private invite link:','แชร์ลิงก์เชิญส่วนตัวของคุณ:'),

-- Copied!
('vi','Copied!','Đã sao chép!'),
('es','Copied!','¡Copiado!'),
('zh','Copied!','已复制！'),
('hi','Copied!','Copy हो गया!'),
('pt','Copied!','Copiado!'),
('fr','Copied!','Copié !'),
('ko','Copied!','복사됐어!'),
('ja','Copied!','コピーした！'),
('th','Copied!','คัดลอกแล้ว!'),

-- Share
('vi','Share','Chia sẻ'),
('es','Share','Compartir'),
('zh','Share','分享'),
('hi','Share','Share करो'),
('pt','Share','Compartilhar'),
('fr','Share','Partager'),
('ko','Share','공유'),
('ja','Share','シェア'),
('th','Share','แชร์'),

-- Back to your invites
('vi','Back to your invites','Quay lại lời mời của bạn'),
('es','Back to your invites','Volver a tus invitaciones'),
('zh','Back to your invites','回到我的邀请'),
('hi','Back to your invites','अपने invites पर वापस जाओ'),
('pt','Back to your invites','Voltar para seus convites'),
('fr','Back to your invites','Retour à tes invitations'),
('ko','Back to your invites','초대장 목록으로'),
('ja','Back to your invites','招待状一覧に戻る'),
('th','Back to your invites','กลับไปที่คำเชิญของคุณ'),

-- Your answer is on its way
('vi','Your answer is on its way','Câu trả lời của bạn đang được gửi đi'),
('es','Your answer is on its way','Tu respuesta está en camino'),
('zh','Your answer is on its way','你的回复已发出'),
('hi','Your answer is on its way','आपका जवाब भेजा जा रहा है'),
('pt','Your answer is on its way','Sua resposta está a caminho'),
('fr','Your answer is on its way','Ta réponse est en route'),
('ko','Your answer is on its way','답장 보내는 중이야'),
('ja','Your answer is on its way','返事を送ってるよ'),
('th','Your answer is on its way','คำตอบของคุณกำลังส่งอยู่'),

-- You picked
('vi','You picked','Bạn đã chọn'),
('es','You picked','Elegiste'),
('zh','You picked','你选了'),
('hi','You picked','आपने चुना'),
('pt','You picked','Você escolheu'),
('fr','You picked','Tu as choisi'),
('ko','You picked','네가 고른 건'),
('ja','You picked','あなたが選んだのは'),
('th','You picked','คุณเลือก'),

-- Your secret admirer is
('vi','Your secret admirer is','Người hâm mộ bí mật của bạn là'),
('es','Your secret admirer is','Tu admirador/a secreto/a es'),
('zh','Your secret admirer is','你的神秘仰慕者是'),
('hi','Your secret admirer is','आपका secret admirer है'),
('pt','Your secret admirer is','Seu admirador secreto é'),
('fr','Your secret admirer is','Ton admirateur secret est'),
('ko','Your secret admirer is','너의 비밀 팬은'),
('ja','Your secret admirer is','あなたの秘密のファンは'),
('th','Your secret admirer is','แฟนลับของคุณคือ'),

-- It's a date with
('vi','It''s a date with','Đây là hẹn hò với'),
('es','It''s a date with','¡Es una cita con'),
('zh','It''s a date with','约会对象是'),
('hi','It''s a date with','Date है'),
('pt','It''s a date with','É um date com'),
('fr','It''s a date with','C''est un rendez-vous avec'),
('ko','It''s a date with','데이트 상대는'),
('ja','It''s a date with','デートの相手は'),
('th','It''s a date with','เดตกับ'),

-- They'll be in touch soon.
('vi','They''ll be in touch soon.','Họ sẽ liên lạc sớm thôi.'),
('es','They''ll be in touch soon.','Pronto se pondrán en contacto.'),
('zh','They''ll be in touch soon.','他/她很快会联系你的。'),
('hi','They''ll be in touch soon.','वो जल्द ही connect करेंगे।'),
('pt','They''ll be in touch soon.','Eles entrarão em contato em breve.'),
('fr','They''ll be in touch soon.','Ils vont te contacter bientôt.'),
('ko','They''ll be in touch soon.','곧 연락이 올 거야.'),
('ja','They''ll be in touch soon.','もうすぐ連絡が来るよ。'),
('th','They''ll be in touch soon.','เขา/เธอจะติดต่อคุณเร็ว ๆ นี้')

ON DUPLICATE KEY UPDATE value = VALUES(value);
