INSERT INTO ui_translations (lang, `key`, value) VALUES

-- A few cute details so your crush knows it's really you.
('vi','A few cute details so your crush knows it''s really you.','Vài thông tin nhỏ xinh để crush biết đây là bạn nha.'),
('es','A few cute details so your crush knows it''s really you.','Unos detalles para que tu crush sepa que eres tú de verdad.'),
('zh','A few cute details so your crush knows it''s really you.','填几个小细节，让 ta 知道真的是你～'),
('hi','A few cute details so your crush knows it''s really you.','बस थोड़े cute details ताकि crush समझे ये सच में तुम हो।'),
('pt','A few cute details so your crush knows it''s really you.','Uns detalhes fofinhos pra seu crush saber que é mesmo você.'),
('fr','A few cute details so your crush knows it''s really you.','Quelques détails mignons pour que ton crush sache que c''est vraiment toi.'),
('ko','A few cute details so your crush knows it''s really you.','진짜 너라는 걸 알 수 있게 귀여운 정보 몇 가지 추가해봐.'),
('ja','A few cute details so your crush knows it''s really you.','あなたが本人だってわかるように、ちょっとかわいい情報を教えてね。'),
('th','A few cute details so your crush knows it''s really you.','ใส่รายละเอียดน่ารัก ๆ สักหน่อยให้ crush รู้ว่าเป็นเธอจริง ๆ นะ'),

-- About you
('vi','About you','Về bạn'),
('es','About you','Sobre ti'),
('zh','About you','关于你'),
('hi','About you','तुम्हारे बारे में'),
('pt','About you','Sobre você'),
('fr','About you','Sur toi'),
('ko','About you','나에 대해'),
('ja','About you','あなたについて'),
('th','About you','เกี่ยวกับเธอ'),

-- Add a few cute details so they know it's really you — then you'll see what they picked.
('vi','Add a few cute details so they know it''s really you — then you''ll see what they picked.','Thêm vài thông tin nhỏ xinh để họ biết đây là bạn — rồi bạn sẽ thấy họ chọn gì nha.'),
('es','Add a few cute details so they know it''s really you — then you''ll see what they picked.','Añade unos detalles para que sepan que eres tú — y luego verás qué eligieron.'),
('zh','Add a few cute details so they know it''s really you — then you''ll see what they picked.','填几个小细节让 ta 知道是你，然后就能看到 ta 选了什么了～'),
('hi','Add a few cute details so they know it''s really you — then you''ll see what they picked.','थोड़े cute details add करो ताकि वो जानें ये तुम हो — फिर देखो उन्होंने क्या choose किया।'),
('pt','Add a few cute details so they know it''s really you — then you''ll see what they picked.','Adicione alguns detalhes pra eles saberem que é você — depois você vai ver o que eles escolheram.'),
('fr','Add a few cute details so they know it''s really you — then you''ll see what they picked.','Ajoute quelques détails pour qu''ils sachent que c''est toi — et tu verras ce qu''ils ont choisi.'),
('ko','Add a few cute details so they know it''s really you — then you''ll see what they picked.','진짜 너라는 걸 알 수 있게 정보 좀 입력해봐 — 그러면 뭘 골랐는지 볼 수 있어.'),
('ja','Add a few cute details so they know it''s really you — then you''ll see what they picked.','あなたが本人ってわかるように情報を入れてね — そしたら相手が選んだものが見られるよ。'),
('th','Add a few cute details so they know it''s really you — then you''ll see what they picked.','ใส่รายละเอียดน่ารัก ๆ ให้เขารู้ว่าเป็นเธอ — แล้วจะได้ดูว่าเขาเลือกอะไร'),

-- Afternoon
('vi','Afternoon','Buổi chiều'),
('es','Afternoon','Tarde'),
('zh','Afternoon','下午'),
('hi','Afternoon','दोपहर'),
('pt','Afternoon','Tarde'),
('fr','Afternoon','Après-midi'),
('ko','Afternoon','오후'),
('ja','Afternoon','午後'),
('th','Afternoon','บ่าย'),

-- Any wish? (optional)
('vi','Any wish? (optional)','Có điều ước gì không? (không bắt buộc)'),
('es','Any wish? (optional)','¿Algún deseo? (opcional)'),
('zh','Any wish? (optional)','有什么心愿吗？（选填）'),
('hi','Any wish? (optional)','कोई इच्छा है? (optional)'),
('pt','Any wish? (optional)','Algum desejo? (opcional)'),
('fr','Any wish? (optional)','Un souhait ? (optionnel)'),
('ko','Any wish? (optional)','바라는 게 있어? (선택 사항)'),
('ja','Any wish? (optional)','何かリクエストある？（なくてもOK）'),
('th','Any wish? (optional)','มีความปรารถนาอะไรไหม? (ไม่บังคับ)'),

-- Contact
('vi','Contact','Liên hệ'),
('es','Contact','Contacto'),
('zh','Contact','联系方式'),
('hi','Contact','Contact'),
('pt','Contact','Contato'),
('fr','Contact','Contact'),
('ko','Contact','연락처'),
('ja','Contact','連絡先'),
('th','Contact','ติดต่อ'),

-- Contact (optional)
('vi','Contact (optional)','Liên hệ (không bắt buộc)'),
('es','Contact (optional)','Contacto (opcional)'),
('zh','Contact (optional)','联系方式（选填）'),
('hi','Contact (optional)','Contact (optional)'),
('pt','Contact (optional)','Contato (opcional)'),
('fr','Contact (optional)','Contact (optionnel)'),
('ko','Contact (optional)','연락처 (선택 사항)'),
('ja','Contact (optional)','連絡先（なくてもOK）'),
('th','Contact (optional)','ติดต่อ (ไม่บังคับ)'),

-- Continue with Google
('vi','Continue with Google','Tiếp tục với Google'),
('es','Continue with Google','Continuar con Google'),
('zh','Continue with Google','用 Google 继续'),
('hi','Continue with Google','Google से जारी रखो'),
('pt','Continue with Google','Continuar com Google'),
('fr','Continue with Google','Continuer avec Google'),
('ko','Continue with Google','Google로 계속하기'),
('ja','Continue with Google','Google で続ける'),
('th','Continue with Google','ดำเนินการต่อด้วย Google'),

-- Craving
('vi','Craving','Thèm'),
('es','Craving','Antojo'),
('zh','Craving','想吃'),
('hi','Craving','Craving'),
('pt','Craving','Vontade'),
('fr','Craving','Envie'),
('ko','Craving','먹고 싶은 거'),
('ja','Craving','食べたいもの'),
('th','Craving','อยากกิน'),

-- Download calendar invite
('vi','Download calendar invite','Tải lịch về'),
('es','Download calendar invite','Descargar invitación al calendario'),
('zh','Download calendar invite','下载日历邀请'),
('hi','Download calendar invite','Calendar invite download करो'),
('pt','Download calendar invite','Baixar convite do calendário'),
('fr','Download calendar invite','Télécharger l''invitation calendrier'),
('ko','Download calendar invite','캘린더 초대장 다운로드'),
('ja','Download calendar invite','カレンダーの招待状をダウンロード'),
('th','Download calendar invite','ดาวน์โหลดคำเชิญในปฏิทิน'),

-- Email me a magic link
('vi','Email me a magic link','Gửi email magic link cho tôi'),
('es','Email me a magic link','Envíame un link mágico'),
('zh','Email me a magic link','给我发一个魔法链接'),
('hi','Email me a magic link','मुझे magic link email करो'),
('pt','Email me a magic link','Me manda um link mágico por email'),
('fr','Email me a magic link','Envoie-moi un lien magique'),
('ko','Email me a magic link','이메일로 매직 링크 보내줘'),
('ja','Email me a magic link','マジックリンクをメールで送って'),
('th','Email me a magic link','ส่ง magic link มาทางอีเมลฉันหน่อย'),

-- Evening
('vi','Evening','Buổi tối'),
('es','Evening','Noche'),
('zh','Evening','晚上'),
('hi','Evening','शाम'),
('pt','Evening','Noite'),
('fr','Evening','Soirée'),
('ko','Evening','저녁'),
('ja','Evening','夜'),
('th','Evening','เย็น'),

-- Make it yours
('vi','Make it yours','Cá nhân hoá nào'),
('es','Make it yours','Hazlo tuyo'),
('zh','Make it yours','来，整成你的风格'),
('hi','Make it yours','इसे अपना बनाओ'),
('pt','Make it yours','Torna seu'),
('fr','Make it yours','Rends-le unique'),
('ko','Make it yours','나만의 스타일로 꾸며봐'),
('ja','Make it yours','あなたらしくカスタマイズ'),
('th','Make it yours','ทำให้เป็นของเธอเลย'),

-- Morning
('vi','Morning','Buổi sáng'),
('es','Morning','Mañana'),
('zh','Morning','早上'),
('hi','Morning','सुबह'),
('pt','Morning','Manhã'),
('fr','Morning','Matin'),
('ko','Morning','아침'),
('ja','Morning','朝'),
('th','Morning','เช้า'),

-- No account yet?
('vi','No account yet?','Chưa có tài khoản à?'),
('es','No account yet?','¿Todavía no tienes cuenta?'),
('zh','No account yet?','还没有账号？'),
('hi','No account yet?','अभी तक account नहीं है?'),
('pt','No account yet?','Ainda não tem conta?'),
('fr','No account yet?','Pas encore de compte ?'),
('ko','No account yet?','아직 계정이 없어?'),
('ja','No account yet?','まだアカウント持ってない？'),
('th','No account yet?','ยังไม่มีบัญชีเหรอ?'),

-- No response yet. We'll let you know the moment they answer.
('vi','No response yet. We''ll let you know the moment they answer.','Chưa có phản hồi. Chúng tôi sẽ báo ngay khi họ trả lời.'),
('es','No response yet. We''ll let you know the moment they answer.','Aún no hay respuesta. Te avisaremos en el momento que contesten.'),
('zh','No response yet. We''ll let you know the moment they answer.','还没有回复呢。ta 一回复我们马上通知你～'),
('hi','No response yet. We''ll let you know the moment they answer.','अभी तक कोई जवाब नहीं। जैसे ही वो reply करें, हम तुम्हें बताएंगे।'),
('pt','No response yet. We''ll let you know the moment they answer.','Nenhuma resposta ainda. A gente avisa assim que eles responderem.'),
('fr','No response yet. We''ll let you know the moment they answer.','Pas encore de réponse. On te préviendra dès qu''ils répondent.'),
('ko','No response yet. We''ll let you know the moment they answer.','아직 답장이 없어. 답하는 순간 바로 알려줄게.'),
('ja','No response yet. We''ll let you know the moment they answer.','まだ返事がないよ。返事が来たらすぐお知らせするね。'),
('th','No response yet. We''ll let you know the moment they answer.','ยังไม่มีการตอบกลับ เราจะแจ้งให้ทราบทันทีที่เขาตอบ'),

-- Not found
('vi','Not found','Không tìm thấy'),
('es','Not found','No encontrado'),
('zh','Not found','找不到'),
('hi','Not found','नहीं मिला'),
('pt','Not found','Não encontrado'),
('fr','Not found','Introuvable'),
('ko','Not found','찾을 수 없음'),
('ja','Not found','見つからない'),
('th','Not found','ไม่พบ'),

-- Open it on this device to continue.
('vi','Open it on this device to continue.','Mở trên thiết bị này để tiếp tục nha.'),
('es','Open it on this device to continue.','Ábrelo en este dispositivo para continuar.'),
('zh','Open it on this device to continue.','在这台设备上打开才能继续哦。'),
('hi','Open it on this device to continue.','जारी रखने के लिए इस device पर खोलो।'),
('pt','Open it on this device to continue.','Abra neste dispositivo para continuar.'),
('fr','Open it on this device to continue.','Ouvre-le sur cet appareil pour continuer.'),
('ko','Open it on this device to continue.','계속하려면 이 기기에서 열어봐.'),
('ja','Open it on this device to continue.','続けるにはこのデバイスで開いてね。'),
('th','Open it on this device to continue.','เปิดในอุปกรณ์นี้เพื่อดำเนินการต่อ'),

-- Other ways to sign in
('vi','Other ways to sign in','Cách đăng nhập khác'),
('es','Other ways to sign in','Otras formas de iniciar sesión'),
('zh','Other ways to sign in','其他登录方式'),
('hi','Other ways to sign in','Sign in करने के और तरीके'),
('pt','Other ways to sign in','Outras formas de entrar'),
('fr','Other ways to sign in','D''autres façons de se connecter'),
('ko','Other ways to sign in','다른 로그인 방법'),
('ja','Other ways to sign in','他のサインイン方法'),
('th','Other ways to sign in','วิธีลงชื่อเข้าใช้อื่น ๆ'),

-- Pick a day
('vi','Pick a day','Chọn ngày nào'),
('es','Pick a day','Elige un día'),
('zh','Pick a day','选个日期'),
('hi','Pick a day','एक दिन चुनो'),
('pt','Pick a day','Escolha um dia'),
('fr','Pick a day','Choisis un jour'),
('ko','Pick a day','날짜 골라봐'),
('ja','Pick a day','日にちを選んでね'),
('th','Pick a day','เลือกวันกันเลย'),

-- Pick an avatar
('vi','Pick an avatar','Chọn avatar nào'),
('es','Pick an avatar','Elige un avatar'),
('zh','Pick an avatar','选个头像'),
('hi','Pick an avatar','एक avatar चुनो'),
('pt','Pick an avatar','Escolha um avatar'),
('fr','Pick an avatar','Choisis un avatar'),
('ko','Pick an avatar','아바타 골라봐'),
('ja','Pick an avatar','アバターを選んでね'),
('th','Pick an avatar','เลือก avatar กันเลย'),

-- Pickup
('vi','Pickup','Đón'),
('es','Pickup','Recogida'),
('zh','Pickup','接送'),
('hi','Pickup','Pickup'),
('pt','Pickup','Buscar'),
('fr','Pickup','Prise en charge'),
('ko','Pickup','픽업'),
('ja','Pickup','迎え'),
('th','Pickup','รับตัว'),

-- Save my profile
('vi','Save my profile','Lưu hồ sơ của tôi'),
('es','Save my profile','Guardar mi perfil'),
('zh','Save my profile','保存我的资料'),
('hi','Save my profile','मेरी profile save करो'),
('pt','Save my profile','Salvar meu perfil'),
('fr','Save my profile','Sauvegarder mon profil'),
('ko','Save my profile','내 프로필 저장'),
('ja','Save my profile','プロフィールを保存する'),
('th','Save my profile','บันทึกโปรไฟล์ของฉัน'),

-- Send my answer
('vi','Send my answer','Gửi câu trả lời'),
('es','Send my answer','Enviar mi respuesta'),
('zh','Send my answer','发送我的回复'),
('hi','Send my answer','मेरा जवाब भेजो'),
('pt','Send my answer','Enviar minha resposta'),
('fr','Send my answer','Envoyer ma réponse'),
('ko','Send my answer','내 답장 보내기'),
('ja','Send my answer','返事を送る'),
('th','Send my answer','ส่งคำตอบของฉัน'),

-- Sent
('vi','Sent','Đã gửi'),
('es','Sent','Enviado'),
('zh','Sent','已发送'),
('hi','Sent','भेज दिया'),
('pt','Sent','Enviado'),
('fr','Sent','Envoyé'),
('ko','Sent','전송됨'),
('ja','Sent','送ったよ'),
('th','Sent','ส่งแล้ว'),

-- Sent as yourself.
('vi','Sent as yourself.','Gửi với tên thật của bạn.'),
('es','Sent as yourself.','Enviado como tú mismo.'),
('zh','Sent as yourself.','以本人身份发送的。'),
('hi','Sent as yourself.','खुद के नाम से भेजा।'),
('pt','Sent as yourself.','Enviado como você mesmo.'),
('fr','Sent as yourself.','Envoyé en ton propre nom.'),
('ko','Sent as yourself.','본인 이름으로 보냈어.'),
('ja','Sent as yourself.','本人として送ったよ。'),
('th','Sent as yourself.','ส่งในชื่อของตัวเองแล้ว'),

-- Sign in
('vi','Sign in','Đăng nhập'),
('es','Sign in','Iniciar sesión'),
('zh','Sign in','登录'),
('hi','Sign in','लॉग इन करो'),
('pt','Sign in','Entrar'),
('fr','Sign in','Se connecter'),
('ko','Sign in','로그인'),
('ja','Sign in','サインイン'),
('th','Sign in','เข้าสู่ระบบ'),

-- Sign in to send someone a date invite.
('vi','Sign in to send someone a date invite.','Đăng nhập để gửi lời mời hẹn hò cho ai đó nhé.'),
('es','Sign in to send someone a date invite.','Inicia sesión para enviarle una invitación a alguien.'),
('zh','Sign in to send someone a date invite.','登录后就能给心仪的人发约会邀请啦。'),
('hi','Sign in to send someone a date invite.','किसी को date invite भेजने के लिए sign in करो।'),
('pt','Sign in to send someone a date invite.','Entre pra mandar um convite de date pra alguém.'),
('fr','Sign in to send someone a date invite.','Connecte-toi pour envoyer une invitation à quelqu''un.'),
('ko','Sign in to send someone a date invite.','누군가에게 데이트 초대장을 보내려면 로그인해봐.'),
('ja','Sign in to send someone a date invite.','デートに誘うにはサインインしてね。'),
('th','Sign in to send someone a date invite.','ลงชื่อเข้าใช้เพื่อส่งคำเชิญเดตให้ใครสักคน'),

-- Start here
('vi','Start here','Bắt đầu từ đây'),
('es','Start here','Empieza aquí'),
('zh','Start here','从这里开始'),
('hi','Start here','यहाँ से शुरू करो'),
('pt','Start here','Comece aqui'),
('fr','Start here','Commence ici'),
('ko','Start here','여기서 시작해'),
('ja','Start here','ここから始めよう'),
('th','Start here','เริ่มที่นี่เลย'),

-- They picked
('vi','They picked','Họ đã chọn'),
('es','They picked','Eligieron'),
('zh','They picked','ta 选了'),
('hi','They picked','उन्होंने चुना'),
('pt','They picked','Eles escolheram'),
('fr','They picked','Ils ont choisi'),
('ko','They picked','상대가 고른 거'),
('ja','They picked','相手が選んだのは'),
('th','They picked','เขาเลือก'),

-- Time of day
('vi','Time of day','Buổi trong ngày'),
('es','Time of day','Momento del día'),
('zh','Time of day','时间段'),
('hi','Time of day','दिन का समय'),
('pt','Time of day','Período do dia'),
('fr','Time of day','Moment de la journée'),
('ko','Time of day','하루 중 시간대'),
('ja','Time of day','時間帯'),
('th','Time of day','ช่วงเวลาของวัน'),

-- Upload your own photo
('vi','Upload your own photo','Tải ảnh của bạn lên'),
('es','Upload your own photo','Sube tu propia foto'),
('zh','Upload your own photo','上传你自己的照片'),
('hi','Upload your own photo','अपनी photo upload करो'),
('pt','Upload your own photo','Suba sua própria foto'),
('fr','Upload your own photo','Envoie ta propre photo'),
('ko','Upload your own photo','내 사진 올리기'),
('ja','Upload your own photo','自分の写真をアップロード'),
('th','Upload your own photo','อัปโหลดรูปของตัวเอง'),

-- Waiting on
('vi','Waiting on','Đang chờ'),
('es','Waiting on','Esperando a'),
('zh','Waiting on','等待中，对方是'),
('hi','Waiting on','इंतज़ार है'),
('pt','Waiting on','Aguardando'),
('fr','Waiting on','En attente de'),
('ko','Waiting on','기다리는 중'),
('ja','Waiting on','待ってるのは'),
('th','Waiting on','รอ'),

-- We couldn't find that invite.
('vi','We couldn''t find that invite.','Chúng tôi không tìm thấy lời mời đó.'),
('es','We couldn''t find that invite.','No pudimos encontrar esa invitación.'),
('zh','We couldn''t find that invite.','找不到这个邀请。'),
('hi','We couldn''t find that invite.','हम वो invite नहीं ढूंढ पाए।'),
('pt','We couldn''t find that invite.','Não conseguimos encontrar esse convite.'),
('fr','We couldn''t find that invite.','On n''a pas trouvé cette invitation.'),
('ko','We couldn''t find that invite.','초대장을 찾을 수가 없어.'),
('ja','We couldn''t find that invite.','その招待状が見つからなかったよ。'),
('th','We couldn''t find that invite.','เราหาคำเชิญนั้นไม่เจอ'),

-- We sent a magic sign-in link to
('vi','We sent a magic sign-in link to','Chúng tôi đã gửi magic link đăng nhập tới'),
('es','We sent a magic sign-in link to','Te enviamos un link mágico para iniciar sesión a'),
('zh','We sent a magic sign-in link to','我们已发送魔法登录链接到'),
('hi','We sent a magic sign-in link to','हमने magic sign-in link भेज दिया'),
('pt','We sent a magic sign-in link to','Enviamos um link mágico de acesso para'),
('fr','We sent a magic sign-in link to','On a envoyé un lien de connexion magique à'),
('ko','We sent a magic sign-in link to','매직 로그인 링크를 보냈어, 받는 사람:'),
('ja','We sent a magic sign-in link to','マジックサインインリンクを送ったよ→'),
('th','We sent a magic sign-in link to','เราส่งลิงก์ลงชื่อเข้าใช้แบบพิเศษไปที่'),

-- What are you craving?
('vi','What are you craving?','Bạn đang thèm gì vậy?'),
('es','What are you craving?','¿Qué se te antoja?'),
('zh','What are you craving?','你现在想吃什么？'),
('hi','What are you craving?','तुम्हें क्या खाने का मन है?'),
('pt','What are you craving?','O que você está com vontade de comer?'),
('fr','What are you craving?','T''as envie de quoi ?'),
('ko','What are you craving?','지금 뭐 먹고 싶어?'),
('ja','What are you craving?','今何が食べたい気分？'),
('th','What are you craving?','ตอนนี้อยากกินอะไรอยู่?'),

-- When
('vi','When','Khi nào'),
('es','When','Cuándo'),
('zh','When','时间'),
('hi','When','कब'),
('pt','When','Quando'),
('fr','When','Quand'),
('ko','When','언제'),
('ja','When','いつ'),
('th','When','เมื่อไหร่'),

-- Where should they pick you up? (optional)
('vi','Where should they pick you up? (optional)','Họ đón bạn ở đâu? (không bắt buộc)'),
('es','Where should they pick you up? (optional)','¿Dónde te pasan buscando? (opcional)'),
('zh','Where should they pick you up? (optional)','让 ta 去哪儿接你？（选填）'),
('hi','Where should they pick you up? (optional)','तुम्हें कहाँ से pick up करें? (optional)'),
('pt','Where should they pick you up? (optional)','Onde eles devem te buscar? (opcional)'),
('fr','Where should they pick you up? (optional)','Où doivent-ils venir te chercher ? (optionnel)'),
('ko','Where should they pick you up? (optional)','어디서 데리러 올까? (선택 사항)'),
('ja','Where should they pick you up? (optional)','どこに迎えに行けばいい？（なくてもOK）'),
('th','Where should they pick you up? (optional)','ให้มารับที่ไหน? (ไม่บังคับ)'),

-- Wish
('vi','Wish','Điều ước'),
('es','Wish','Deseo'),
('zh','Wish','心愿'),
('hi','Wish','Wish'),
('pt','Wish','Desejo'),
('fr','Wish','Souhait'),
('ko','Wish','바람'),
('ja','Wish','リクエスト'),
('th','Wish','ความปรารถนา'),

-- You sent this anonymously.
('vi','You sent this anonymously.','Bạn đã gửi cái này ẩn danh.'),
('es','You sent this anonymously.','Lo enviaste de forma anónima.'),
('zh','You sent this anonymously.','你是匿名发送的。'),
('hi','You sent this anonymously.','तुमने ये anonymously भेजा।'),
('pt','You sent this anonymously.','Você enviou isso anonimamente.'),
('fr','You sent this anonymously.','Tu l''as envoyé anonymement.'),
('ko','You sent this anonymously.','이거 익명으로 보냈어.'),
('ja','You sent this anonymously.','これは匿名で送ったよ。'),
('th','You sent this anonymously.','คุณส่งสิ่งนี้โดยไม่เปิดเผยตัวตน'),

-- Your contact (optional)
('vi','Your contact (optional)','Liên hệ của bạn (không bắt buộc)'),
('es','Your contact (optional)','Tu contacto (opcional)'),
('zh','Your contact (optional)','你的联系方式（选填）'),
('hi','Your contact (optional)','तुम्हारा contact (optional)'),
('pt','Your contact (optional)','Seu contato (opcional)'),
('fr','Your contact (optional)','Ton contact (optionnel)'),
('ko','Your contact (optional)','내 연락처 (선택 사항)'),
('ja','Your contact (optional)','あなたの連絡先（なくてもOK）'),
('th','Your contact (optional)','ข้อมูลติดต่อของคุณ (ไม่บังคับ)'),

-- address or Google Maps link
('vi','address or Google Maps link','địa chỉ hoặc link Google Maps'),
('es','address or Google Maps link','dirección o enlace de Google Maps'),
('zh','address or Google Maps link','地址或 Google Maps 链接'),
('hi','address or Google Maps link','address या Google Maps link'),
('pt','address or Google Maps link','endereço ou link do Google Maps'),
('fr','address or Google Maps link','adresse ou lien Google Maps'),
('ko','address or Google Maps link','주소 또는 Google Maps 링크'),
('ja','address or Google Maps link','住所か Google Maps のリンク'),
('th','address or Google Maps link','ที่อยู่หรือลิงก์ Google Maps'),

-- answered!
('vi','answered!','đã trả lời rồi!'),
('es','answered!','¡ya respondió!'),
('zh','answered!','回复啦！'),
('hi','answered!','जवाब दे दिया!'),
('pt','answered!','respondeu!'),
('fr','answered!','a répondu !'),
('ko','answered!','답장했어!'),
('ja','answered!','返事が来たよ！'),
('th','answered!','ตอบแล้ว!'),

-- at
('vi','at','lúc'),
('es','at','a las'),
('zh','at','在'),
('hi','at','पर'),
('pt','at','às'),
('fr','at','à'),
('ko','at','에'),
('ja','at','に'),
('th','at','ที่'),

-- has a crush on u
('vi','has a crush on u','đang thích u lắm đó'),
('es','has a crush on u','tiene un crush en ti bb'),
('zh','has a crush on u','喜欢你啦 u'),
('hi','has a crush on u','तुम पर crush है 😍'),
('pt','has a crush on u','tá afim de vc bb'),
('fr','has a crush on u','a le béguin pour toi bb'),
('ko','has a crush on u','너한테 반했나봐 ㅋㅋ'),
('ja','has a crush on u','あなたのこと好きみたい💓'),
('th','has a crush on u','มีใจให้ u อยู่นะ'),

-- has a crush on you
('vi','has a crush on you','đang thích bạn đó'),
('es','has a crush on you','tiene un crush en ti'),
('zh','has a crush on you','喜欢你'),
('hi','has a crush on you','तुम पर crush है'),
('pt','has a crush on you','está a fim de você'),
('fr','has a crush on you','a le béguin pour toi'),
('ko','has a crush on you','당신에게 반했나 봐요'),
('ja','has a crush on you','あなたのことが好きみたい'),
('th','has a crush on you','มีใจให้คุณอยู่นะ'),

-- i'm a sucker for tacos and bad puns
('vi','i''m a sucker for tacos and bad puns','tôi nghiện tacos và những câu đùa dở tệ'),
('es','i''m a sucker for tacos and bad puns','soy un fan de los tacos y los chistes malos'),
('zh','i''m a sucker for tacos and bad puns','我超爱tacos和冷笑话'),
('hi','i''m a sucker for tacos and bad puns','मुझे tacos और बेकार jokes से बहुत प्यार है'),
('pt','i''m a sucker for tacos and bad puns','sou apaixonado por tacos e trocadilhos ruins'),
('fr','i''m a sucker for tacos and bad puns','je craque pour les tacos et les mauvais jeux de mots'),
('ko','i''m a sucker for tacos and bad puns','타코랑 아재개그라면 못 참지'),
('ja','i''m a sucker for tacos and bad puns','タコスとダジャレには目がないんだよね'),
('th','i''m a sucker for tacos and bad puns','ฉันชอบทาโคสและมุกตลกห่วย ๆ มาก'),

-- map
('vi','map','bản đồ'),
('es','map','mapa'),
('zh','map','地图'),
('hi','map','map'),
('pt','map','mapa'),
('fr','map','carte'),
('ko','map','지도'),
('ja','map','マップ'),
('th','map','แผนที่'),

-- pick a spot
('vi','pick a spot','chọn địa điểm đi'),
('es','pick a spot','elige un lugar'),
('zh','pick a spot','选个地方'),
('hi','pick a spot','कोई जगह चुनो'),
('pt','pick a spot','escolha um lugar'),
('fr','pick a spot','choisis un endroit'),
('ko','pick a spot','장소 골라봐'),
('ja','pick a spot','場所を選んでね'),
('th','pick a spot','เลือกที่กันเลย'),

-- requests your company
('vi','requests your company','muốn đi cùng bạn'),
('es','requests your company','quiere que los acompañes'),
('zh','requests your company','想邀请你一起'),
('hi','requests your company','तुम्हारी साथ चाहता/चाहती है'),
('pt','requests your company','quer a sua companhia'),
('fr','requests your company','aimerait ta compagnie'),
('ko','requests your company','같이 가자고 해'),
('ja','requests your company','一緒に来てほしいって'),
('th','requests your company','อยากให้คุณไปด้วย'),

-- surprise me
('vi','surprise me','bất ngờ tôi đi'),
('es','surprise me','sorpréndeme'),
('zh','surprise me','给我个惊喜'),
('hi','surprise me','मुझे surprise करो'),
('pt','surprise me','me surpreenda'),
('fr','surprise me','surprends-moi'),
('ko','surprise me','나 좀 놀래켜봐'),
('ja','surprise me','サプライズして！'),
('th','surprise me','เซอร์ไพรส์ฉันเลย')

ON DUPLICATE KEY UPDATE value = VALUES(value);
