INSERT INTO ui_translations (lang, `key`, value) VALUES
('vi','Send your crush a date — anonymously, adorably.','Rủ crush đi hẹn — ẩn danh mà vẫn cute.'),
('vi','Real life, but make it a date','Đời thường thôi, nhưng biến thành một buổi hẹn'),
('vi','your name','tên của bạn'),
('vi','you@email.com','email của bạn'),
('vi','pick a password','tạo mật khẩu'),
('vi','password','mật khẩu'),
('vi','Pick a password — you''ll use it to sign back in.','Tạo mật khẩu để lần sau đăng nhập lại nha.'),
('vi','Check your email — we sent a sign-in link to','Check email nha — tụi mình đã gửi link đăng nhập tới'),
('vi','Open it to keep going.','Mở link đó để đi tiếp.'),

('vi','Send a crush invite','Gửi lời mời cho crush'),
('vi','How will you send it?','Bạn muốn gửi cho người ấy kiểu nào?'),
('vi','Email it to them','Gửi email cho người ấy'),
('vi','I''ll share the link','Tự mình gửi link'),
('vi','Their email','email của người ấy'),
('vi','Their name','tên người ấy'),
('vi','A little message (optional)','nhắn nhủ xíu (không bắt buộc)'),
('vi','When should they pick?','Cho người ấy chọn lúc nào?'),
('vi','Any time (final)','Lúc nào cũng được (chốt luôn)'),
('vi','They propose, I confirm','Người ấy đề xuất, mình chốt'),
('vi','Send anonymously (a secret admirer)','Gửi ẩn danh (secret admirer mode)'),
('vi','Reveal me after they respond','Cho người ấy biết mình là ai sau khi trả lời'),
('vi','A spot to suggest?','Có chỗ nào muốn gợi ý không?'),
('vi','I''m open — they pick','Mình thoải mái — để người ấy chọn'),
('vi','Let''s do a vibe','Chọn theo vibe đi'),
('vi','restaurant name','tên quán'),
('vi','maps link (optional)','link Google Maps (không bắt buộc)'),
('vi','cuisine','gu ăn uống'),
('vi','Other','Khác'),
('vi','Add another place','thêm quán khác'),
('vi','Create my invite','Tạo lời mời cute này'),
('vi','Creating as','Đang tạo dưới tên'),
('vi','not you?','không phải bạn hả?'),
('vi','use another email','đổi email'),
('vi','Map preview','Xem map trước'),
('vi','Lunch','Ăn trưa'),
('vi','Dinner','Ăn tối'),
('vi','Brunch','Brunch'),
('vi','Drinks','Đi uống'),
('vi','Hotel','Khách sạn'),
('vi','hotel name','tên khách sạn'),
('vi','Remove','Xoá'),
('vi','Italian','Ý'),
('vi','Japanese','Nhật'),
('vi','Korean','Hàn'),
('vi','Vietnamese','Việt'),
('vi','Thai','Thái'),
('vi','Chinese','Trung'),
('vi','Mexican','Mexico'),
('vi','Indian','Ấn'),
('vi','American','Mỹ'),
('vi','French','Pháp'),

('vi','Your invites','Kèo bạn đã gửi'),
('vi','Send a new crush invite','Gửi lời mời mới cho crush'),
('vi','No invites yet. Send your first one above.','Chưa có kèo nào. Tạo một lời mời đi nè!'),
('vi','A secret crush','Một crush bí mật'),
('vi','Needs you','Đợi bạn chốt'),
('vi','Your invite is ready','Lời mời sẵn sàng rồi'),
('vi','Share this private link with','Gửi link riêng này cho'),
('vi','Share your private invite link:','Gửi link mời riêng của bạn:'),
('vi','Back to your invites','Quay lại các lời mời'),

('vi','Your answer is on its way','Câu trả lời đang bay tới rồi'),
('vi','You picked','Bạn đã chọn'),
('vi','Your secret admirer is','Secret admirer của bạn là'),
('vi','It''s a date with','Có hẹn với'),
('vi','They''ll be in touch soon.','Người ấy sẽ nhắn bạn sớm nha.'),

('vi','A few cute details so your crush knows it''s really you.','Vài chi tiết nhỏ xinh để crush biết đúng là bạn nha.'),
('vi','About you','Về bạn nè'),
('vi','Add a few cute details so they know it''s really you — then you''ll see what they picked.','Thêm vài chi tiết nhỏ để người ấy biết đúng là bạn — rồi xem người ấy chọn gì nha.'),
('vi','Any wish? (optional)','Muốn nhắn thêm gì không? (không bắt buộc)'),
('vi','Contact','Cách liên lạc'),
('vi','Contact (optional)','Cách liên lạc (không bắt buộc)'),
('vi','Email me a magic link','Gửi magic link qua email cho mình'),
('vi','No response yet. We''ll let you know the moment they answer.','Chưa có phản hồi. Người ấy trả lời là mình báo bạn liền.'),
('vi','Open it on this device to continue.','Mở trên thiết bị này để tiếp tục nha.'),
('vi','Other ways to sign in','Cách đăng nhập khác'),
('vi','Pick a day','Chọn ngày đi nè'),
('vi','Pick an avatar','Chọn avatar nè'),
('vi','Save my profile','Lưu profile của mình'),
('vi','Send my answer','Gửi câu trả lời của mình'),
('vi','Sent as yourself.','Đã gửi bằng danh tính thật rồi.'),
('vi','Sign in to send someone a date invite.','Đăng nhập để gửi lời mời hẹn hò cho người ấy nha.'),
('vi','Start here','Bắt đầu ở đây'),
('vi','They picked','Người ấy đã chọn'),
('vi','We couldn''t find that invite.','Không tìm thấy lời mời này rồi.'),
('vi','We sent a magic sign-in link to','Magic link đã được gửi tới'),
('vi','What are you craving?','Bạn đang thèm gì nè?'),
('vi','Pick a vibe','Chọn vibe cho buổi hẹn'),
('vi','Where should they pick you up? (optional)','Muốn người ấy đón ở đâu? (không bắt buộc)'),
('vi','You sent this anonymously.','Bạn đã gửi ẩn danh rồi.'),
('vi','Your contact (optional)','Cách liên lạc của bạn (không bắt buộc)'),
('vi','has a crush on u','đang crush u đó'),
('vi','has a crush on you','đang crush bạn đó'),
('vi','i''m a sucker for tacos and bad puns','mê đồ ngon và mấy câu đùa hơi nhạt'),
('vi','pick a spot','chọn chỗ đi nè'),
('vi','requests your company','muốn rủ bạn đi cùng'),
('vi','surprise me','làm mình bất ngờ đi')
ON DUPLICATE KEY UPDATE value = VALUES(value);
